//
//  InjectedResolver.swift
//  DependencyInjection
//
//  Created by Tyler Thompson on 7/28/25.
//

/// The backing resolver for the ``Injected(_:)-swift.macro`` macro.
///
/// You do not create this type directly. It is generated by the `@Injected` macro expansion.
/// Each property access calls the factory through ``Container/current``, producing a fresh
/// value every time.
///
/// For throwing factories the `Value` is `Result<D, any Error>`.
/// For async factories the `Value` is `Task<D, Never>` or `Task<D, any Error>`.
public struct InjectedResolver<Value, Factory: Sendable>: Sendable {
    let factory: Factory
    let getter: @Sendable () -> Value
    public init(_ factory: Factory, file: String = #file, line: UInt = #line, function: String = #function) where Factory == SyncFactory<Value> {
        getter = { factory(file: file, line: line, function: function) }
        self.factory = factory
    }

    public init<D>(_ factory: Factory, file: String = #file, line: UInt = #line, function: String = #function) where Factory == SyncThrowingFactory<D>, Value == Result<D, any Error> {
        getter = { Result { try factory(file: file, line: line, function: function) } }
        self.factory = factory
    }

    public init<D>(_ factory: Factory, file: String = #file, line: UInt = #line, function: String = #function) where Factory == AsyncFactory<D>, Value == Task<D, Never> {
        getter = { Task { await factory(file: file, line: line, function: function) } }
        self.factory = factory
    }

    public init<D>(_ factory: Factory, file: String = #file, line: UInt = #line, function: String = #function) where Factory == AsyncThrowingFactory<D>, Value == Task<D, any Error> {
        getter = { Task { try await factory(file: file, line: line, function: function) } }
        self.factory = factory
    }

    /// The resolved dependency value. Calls the factory on every access.
    public var wrappedValue: Value {
        getter()
    }

    /// The underlying factory, accessible via the `$` prefix on the annotated property.
    public var projectedValue: Factory {
        factory
    }
}
