//
//  LazyInjectedResolver.swift
//  DependencyInjection
//
//  Created by Tyler Thompson on 7/29/25.
//

import Foundation

/// The backing resolver for the ``LazyInjected(_:)-swift.macro`` macro.
///
/// You do not create this type directly. It is generated by the `@LazyInjected` macro expansion.
/// The dependency is resolved on first property access and cached for subsequent reads.
/// Access is thread-safe via an internal lock.
///
/// For async factories, the async task starts eagerly at init time, but the result
/// is only read (and cached) on first property access.
public final class LazyInjectedResolver<Value, Factory: Sendable> {
    let factory: Factory
    let getter: @Sendable () -> Value
    let cleanup: () -> Void
    private let lock = NSRecursiveLock()

    public init(_ factory: Factory, file: String = #file, line: UInt = #line, function: String = #function) where Factory == SyncFactory<Value> {
        getter = { factory(file: file, line: line, function: function) }
        self.factory = factory
        cleanup = { }
    }

    public init<D>(_ factory: Factory, file: String = #file, line: UInt = #line, function: String = #function) where Factory == SyncThrowingFactory<D>, Value == Result<D, any Error> {
        getter = { Result { try factory(file: file, line: line, function: function) } }
        self.factory = factory
        cleanup = { }
    }

    public init<D>(_ factory: Factory, file: String = #file, line: UInt = #line, function: String = #function) where Factory == AsyncFactory<D>, Value == Task<D, Never> {
        let task = Task { await factory(file: file, line: line, function: function) }
        getter = { task }
        self.factory = factory
        cleanup = task.cancel
    }

    public init<D>(_ factory: Factory, file: String = #file, line: UInt = #line, function: String = #function) where Factory == AsyncThrowingFactory<D>, Value == Task<D, any Error> {
        let task = Task { try await factory(file: file, line: line, function: function) }
        getter = { task }
        self.factory = factory
        cleanup = task.cancel
    }

    private var _wrappedValue: Value?

    /// The resolved dependency value. Resolved on first access, then cached.
    public var wrappedValue: Value {
        get {
            lock.lock()
            defer { lock.unlock() }

            if let _wrappedValue {
                return _wrappedValue
            }

            let dependency = getter()
            _wrappedValue = dependency
            return dependency
        }
    }

    /// The underlying factory, accessible via the `$` prefix on the annotated property.
    public var projectedValue: Factory {
        factory
    }
}
